#!/usr/bin/env python

import os, sys, imp, string, getopt
from optparse import OptionParser
import pdb
import os.path

__selfpath__ = os.path.abspath(os.path.dirname(__file__))

sys.path.append(__selfpath__ + "/modules")

import dabus.config
import dabus.util
from dabus.log import logger
from dabus.log import set_log_level, logger
from dabus.version import __version__, __maintainer__

# This block ensures that ^C interrupts are handled quietly.
try:
    import signal

    def exithandler(signum,frame):
        signal.signal(signal.SIGINT, signal.SIG_IGN)
        signal.signal(signal.SIGTERM, signal.SIG_IGN)
        sys.exit(1)

    signal.signal(signal.SIGINT, exithandler)
    signal.signal(signal.SIGTERM, exithandler)
    if hasattr(signal, 'SIGPIPE'):
                signal.signal(signal.SIGPIPE, signal.SIG_DFL)

except KeyboardInterrupt:
        sys.exit(1)

def main(argv):

    if os.getuid() != 0:
        print "This script requires root privileges to operate"
        sys.exit(2)
    usage = "usage: %prog [options] command [cmd_options]"
    description = ""

    parser = OptionParser(
        usage=usage, version=__version__, description=description
    )
    parser.disable_interspersed_args()
    parser.add_option(
        "-d", "--debug", action="store_true", dest="debug",
        default=False, help=("enable debug messages")
    )
    parser.add_option(
        "-q", "--quiet", action="store_true", dest="quiet",
        default=False, help="don't print status messages to stdout"
    )
    parser.add_option(
        "--traceback", action="store_true", dest="trace", default=False,
        help="print full traceback on exceptions"
        )
    parser.add_option(
        "--disable-colors", action="store_true", dest="color_disable",
        default=(os.name == 'nt' or not sys.stdout.isatty()),
        help="disable colors in the output of commands"
    )

    (options, args) = parser.parse_args()

    if len(args) < 1:
        parser.error("No command was given")

    #utils.DISABLE_COLORS = options.color_disable

    # set log level
    if options.quiet:
        set_log_level('WARNING')
    elif options.debug:
        set_log_level('DEBUG')

    cmd = args[0]

    conf = dabus.config.DabusConf(os.path.expanduser('~/.dabusrc'))

    try:
        dabus.util.exec_command(cmd, conf, args[1:])
    except dabus.util.UnknownCommandError:
        logger.error("dabus: Command %s not found" % cmd)
    except SystemExit:
        sys.exit()
    except:
        import traceback
        if options.trace:
            traceback.print_exc()
        else:
            formatted_lines = traceback.format_exc().splitlines()
            logger.error(formatted_lines[-1])
        sys.exit(1)

if __name__ == "__main__":
    main(sys.argv[1:])
